### ISSUE TITLE
How to include external handlebars templates?

### ISSUE THREAD

**Issue by petrocket** [elving/brunch-with-hipsters#9]
This is probably really basic but I can't seem to find an example somewhere on how to render a .hbs template in app/views/templates

In the Hackerank app I see there is a .hbs template and I see a call to view.render() but when I just try to render a view with an external .hbs template nothing comes out.

In my index.html I have a div
<div class="myview"></div>

And in my index.coffee I create the view
myview = new MyView()

The view class has the template member function defined like so
template: require 'views/templates/myview'

I also have an app/views/templates/myview.hbs with 'Hello world' in it but I must be missing something because it doesn't get inserted into index.html - what's the preferred way to get an external .hbs template to render in to index.html?

**Comment by petrocket** [comment]
oh man. does this mean i'm not a hipster? dag yo.

**Comment by elving** [comment]
The Hackerank app uses an old version of the Brunch with Hipsters skeleton. I had a custom `View` class that had a `template` property and a simple `render` method (https://github.com/elving/brunch-with-hipsters/blob/2755050ce1532aac510f3730244de8c24be0833b/app/lib/view.coffee). 

I decided to remove it to keep things simple. To render a Handlebar template using a Backbone View you can do something like:

```
render: ->
    template = require 'templates/template_name'
    @$el.html template @model?.attributes
```

And yes, you are a hipster because you used the expresion "dag yo".

![](http://s3.amazonaws.com/rapgenius/hipster-barista-template.jpg)

**Comment by petrocket** [comment]
Thank God I haven't lost my hipster status! It's working now, apparently the 'scaffolt generate view' command doesn't create an 'el' class member, but a 'className' member so when I was trying to render the 'el' member wasn't properly defined.  I added el: '.myclass' to the class definition and it appears to be working - final code is now essentially:

```
module.exports = class MyView extends Backbone.View
    className: 'myview'
    el: '.myview'
    template: require 'views/templates/myview'

    initialize: ->
        @render()

    render: ->
        @$el.html @template @model?.attributes
```
